meta_product_name: “WanderWise”

meta_title: “WanderWise – Your ultimate journey organizer!”

meta_description: “Fantastic description for a fantastic website!!”

meta_image: “aaaaa.jpg”

twitter_account: “@product_twitter_account”
